# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170109_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='award_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
