# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20161105_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_private', 'Can view non-public projects'),)},
        ),
    ]
