# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20161208_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='agilebpa',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('Labor Hours', 'Labor Hours'), ('Time and Materials', 'Time and Materials')], max_length=200, null=True),
        ),
    ]
