# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_buy_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendors', models.ManyToManyField(blank=True, to='projects.Vendor')),
            ],
        ),
        migrations.AlterField(
            model_name='buy',
            name='procurement_method',
            field=models.CharField(choices=[('agile_bpa', 'Agile Development Services BPA'), ('micropurchase', 'Micro-purchase Platform')], max_length=100),
        ),
        migrations.AddField(
            model_name='buy',
            name='procurement_method_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProcurementMethod'),
        ),
    ]
