# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 17:54
from __future__ import unicode_literals

from django.db import migrations

def link_procurement_methods(apps, schema_editor):
    Buy = apps.get_model('projects', 'Buy')
    ProcurementMethod = apps.get_model('projects', 'ProcurementMethod')
    for buy in Buy.objects.all():
        pm, created = ProcurementMethod.objects.get_or_create(
            name=buy.get_procurement_method_display
        )
        buy.procurement_method_link = pm
        buy.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170117_1752'),
    ]

    operations = [
        migrations.RunPython(link_procurement_methods)
    ]
