# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20161105_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaa',
            name='signed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
