# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='dollars',
            field=models.IntegerField(null=True),
        ),
    ]
