# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_buy_procurement_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='procurement_method_link',
            new_name='procurement_method',
        ),
    ]
