# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170117_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementmethod',
            name='short_name',
            field=models.CharField(default='agile_bpa', help_text='This should correspond to the folder name used for this procurment method in the templates.', max_length=30),
            preserve_default=False,
        ),
    ]
