# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20161118_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='projects.Project'),
        ),
    ]
