# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20161118_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='base_period_length',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='option_period_length',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='option_periods',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='dollars',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
