# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_procurementmethod_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iaa',
            name='dollars',
        ),
        migrations.AddField(
            model_name='iaa',
            name='cogs_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cost of Goods Sold'),
        ),
        migrations.AddField(
            model_name='iaa',
            name='non_cogs_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cost of Team Labor'),
        ),
        migrations.AlterField(
            model_name='iaa',
            name='authority',
            field=models.CharField(blank=True, choices=[('asf', 'Acquisition Services Fund'), ('economy', 'Economy Act')], max_length=100, null=True),
        ),
    ]
