# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alternatecontractingofficerrepresentative'),
    ]

    operations = [
        migrations.AddField(
            model_name='agilebpa',
            name='alternate_contracting_officer_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.AlternateContractingOfficerRepresentative'),
        ),
    ]
