# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_agilebpa_alternate_contracting_officer_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='agilebpa',
            name='security_clearance_required',
            field=models.BooleanField(default=False),
        ),
    ]
