# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20161122_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='base_period_length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='option_period_length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
