# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20170117_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iaa',
            name='expires_on',
        ),
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.CharField(default='123 agency st.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='business_partner_number',
            field=models.IntegerField(default=123456, help_text='This may be a BPN, a DUNS number, or a Dept. of Defense Activity Address Code (DoDAAC). Including the +4 for the number is also accepted.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='business_type_event_code',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='component_tas_number',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='location_code',
            field=models.IntegerField(default=123456, help_text='For more information, see https://tfm.fiscal.treasury.gov/v1/p2/c330.html', verbose_name='Agency Location Code (ALC)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='object_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyoffice',
            name='address',
            field=models.CharField(default='456 agency office rd.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iaa',
            name='assisted_acquisition',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iaa',
            name='funding_canceled_on',
            field=models.DateField(blank=True, help_text='The cancellation date is the fifth year from the expiration date (the last date the payment must be disbursed)', null=True),
        ),
        migrations.AddField(
            model_name='iaa',
            name='funding_expires_on',
            field=models.DateField(blank=True, help_text='The last date an obligation can occur.', null=True),
        ),
        migrations.AddField(
            model_name='iaa',
            name='performance_begins',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iaa',
            name='performance_ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iaa',
            name='authority',
            field=models.CharField(blank=True, choices=[('asf', 'Acquisition Services Fund'), ('economy', 'Economy Act'), ('franchise', 'Franchise Fund'), ('revolving', 'Revolving Fund'), ('working_capital', 'Working Capital Fund')], max_length=100, null=True),
        ),
    ]
