# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 15:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_agilebpa_security_clearance_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='agilebpa',
            name='skills_needed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='micropurchase',
            name='skills_needed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='openmarket',
            name='skills_needed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='software',
            name='skills_needed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
