# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20161122_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dollars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
