# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170118_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='business_type_event_code',
        ),
        migrations.AddField(
            model_name='agency',
            name='business_event_type_code',
            field=models.CharField(default='abcd1234', help_text='An 8-character alphanumeric code indicating the type of activity (e.g. payments, collections, investments) taking place. For more information, see https://www.fiscal.treasury.gov/fsservices/gov/acctg/cars/factsheet_betc.htm', max_length=8),
            preserve_default=False,
        ),
    ]
