# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20161223_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='agilebpa',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='micropurchase',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openmarket',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
