# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_dollars'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='procurement_method',
            field=models.CharField(choices=[('Agile BPA', 'Agile BPA'), ('Micro-Purchase', 'Micro-Purchase')], default='To Be Determined', max_length=200),
        ),
    ]
