# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20161227_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='agilebpa',
            name='google_drive_folder',
            field=models.URLField(blank=True, null=True),
        ),
    ]
