# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_buy_procurement_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='contractual_history',
            field=models.TextField(default='This is the first contract for this functionality.'),
        ),
    ]
