# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20170123_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iaa',
            name='cogs_amount',
        ),
        migrations.RemoveField(
            model_name='iaa',
            name='non_cogs_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dollars',
        ),
        migrations.AddField(
            model_name='iaa',
            name='budget',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='cogs_amount',
            field=models.IntegerField(default=2000, verbose_name='Cost of Goods Sold'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='non_cogs_amount',
            field=models.IntegerField(default=2000, verbose_name='Cost of Team Labor'),
            preserve_default=False,
        ),
    ]
