# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_buy_contractual_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='rfq_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
