# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_agilebpa_google_drive_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agilebpa',
            name='procurement_method',
            field=models.CharField(choices=[('agile_bpa', 'Agile Development Services BPA'), ('micropurchase', 'Micro-purchase')], default='agile_bpa', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='micropurchase',
            name='procurement_method',
            field=models.CharField(choices=[('agile_bpa', 'Agile Development Services BPA'), ('micropurchase', 'Micro-purchase')], default='micropurchase', editable=False, max_length=200),
        ),
    ]
