# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20170123_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaa',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
