# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20170123_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='dollars',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='cogs_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cost of Goods Sold'),
        ),
        migrations.AlterField(
            model_name='project',
            name='non_cogs_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cost of Team Labor'),
        ),
    ]
