# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20161229_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='agilebpa',
            name='interview_questions',
            field=models.TextField(blank=True, help_text='Document: Oral Interview Questions', null=True),
        ),
        migrations.AddField(
            model_name='agilebpa',
            name='pws',
            field=models.TextField(blank=True, help_text='Document: Performance Work Statement', null=True, verbose_name='Performance Work Statement'),
        ),
        migrations.AddField(
            model_name='agilebpa',
            name='rfq',
            field=models.TextField(blank=True, help_text='Document: Request for Quotations', null=True, verbose_name='Request for Quotations'),
        ),
    ]
