# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20161230_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='agilebpa',
            name='question_period_length',
            field=models.PositiveSmallIntegerField(blank=True, default=7, help_text='Length is measured in calendar days.', null=True),
        ),
        migrations.AddField(
            model_name='agilebpa',
            name='submission_period_length',
            field=models.PositiveSmallIntegerField(blank=True, default=14, help_text='Length is measured in calendar days.', null=True),
        ),
    ]
