# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 02:02
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0018_auto_20161230_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dollars', models.PositiveIntegerField(null=True)),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=list, null=True, size=None)),
                ('skills_needed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=list, null=True, size=None)),
                ('public', models.BooleanField(default=False)),
                ('amount_of_competition', models.IntegerField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('contractual_history', models.TextField(default='This is the first contract for this functionality.')),
                ('base_period_length', models.CharField(blank=True, max_length=100, null=True)),
                ('option_periods', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('option_period_length', models.CharField(blank=True, max_length=100, null=True)),
                ('question_period_length', models.PositiveSmallIntegerField(blank=True, default=7, help_text='Length is measured in calendar days.', null=True)),
                ('submission_period_length', models.PositiveSmallIntegerField(blank=True, default=14, help_text='Length is measured in calendar days.', null=True)),
                ('naics_code', models.IntegerField(blank=True, null=True, verbose_name='NAICS Code')),
                ('procurement_method', models.CharField(choices=[('agile_bpa', 'Agile Development Services BPA'), ('micropurchase', 'Micro-purchase Platform')], max_length=200)),
                ('set_aside_status', models.CharField(blank=True, choices=[('AbilityOne', 'AbilityOne'), ('HUBZone Small Business', 'HUBZone Small Business'), ('Multiple Small Business Categories', 'Multiple Small Business Categories'), ('Other Than Small', 'Other Than Small'), ('Service Disabled Veteran-owned Small Business', 'Service Disabled Veteran-owned Small Business'), ('Small Business', 'Small Business'), ('Small Disadvantaged Business (includes Section 8a)', 'Small Disadvantaged Business (includes Section 8a)'), ('Veteran-Owned Small Business', 'Veteran-Owned Small Business'), ('Woman-Owned Small Business', 'Woman-Owned Small Business')], max_length=200, null=True, verbose_name='Set-aside Status')),
                ('competition_strategy', models.CharField(blank=True, choices=[('A/E Procedures', 'A/E Procedures'), ('Competed under SAP', 'Competed under SAP'), ('Competitive Delivery Order Fair Opportunity Provided', 'Competitive Delivery Order Fair Opportunity Provided'), ('Competitive Schedule Buy', 'Competitive Schedule Buy'), ('Fair Opportunity', 'Fair Opportunity'), ('Follow On to Competed Action (FAR 6.302-1)', 'Follow On to Competed Action (FAR 6.302-1)'), ('Follow On to Competed Action', 'Follow On to Competed Action'), ('Full and Open after exclusion of sources (competitive small business         set-asides, competitive 8a)', 'Full and Open after exclusion of sources (competitive small         business set-asides, competitive 8a)'), ('Full and Open Competition Unrestricted', 'Full and Open Competition Unrestricted'), ('Full and Open Competition', 'Full and Open Competition'), ('Limited Sources FSS Order', 'Limited Sources FSS Order'), ('Limited Sources', 'Limited Sources'), ('Non-Competitive Delivery Order', 'Non-Competitive Delivery Order'), ('Not Available for Competition (e.g., 8a sole source, HUBZone &         SDVOSB sole source, Ability One, all > SAT)', 'Not Available for Competition (e.g., 8a sole source, HUBZone &         SDVOSB sole source, Ability One, all > SAT)'), ('Not Competed (e.g., sole source, urgency, etc., all > SAT)', 'Not Competed (e.g., sole source, urgency, etc., all > SAT)'), ('Not Competed under SAP (e.g., Urgent, Sole source, Logical         Follow-On, 8a, HUBZone & SDVOSB sole source, all < SAT)', 'Not Competed under SAP (e.g., Urgent, Sole source, Logical         Follow-On, 8a, HUBZone & SDVOSB sole source, all < SAT)'), ('Partial Small Business Set-Aside', 'Partial Small Business Set-Aside'), ('Set-Aside', 'Set-Aside'), ('Sole Source', 'Sole Source')], max_length=200, null=True)),
                ('contract_type', models.CharField(blank=True, choices=[('Labor Hours', 'Labor Hours'), ('Time and Materials', 'Time and Materials')], max_length=200, null=True)),
                ('rfq_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='RFQ ID')),
                ('github_repository', models.URLField(blank=True, null=True)),
                ('google_drive_folder', models.URLField(blank=True, null=True)),
                ('security_clearance_required', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('qasp', models.TextField(blank=True, help_text='Document: Quality Assurance Surveillance Plan', null=True, verbose_name='Quality Assurance Surveillance Plan')),
                ('acquisition_plan', models.TextField(blank=True, help_text='Document: Acquisition Plan', null=True)),
                ('market_research', models.TextField(blank=True, help_text='Document: Market Research', null=True)),
                ('pws', models.TextField(blank=True, help_text='Document: Performance Work Statement', null=True, verbose_name='Performance Work Statement')),
                ('rfq', models.TextField(blank=True, help_text='Document: Request for Quotations', null=True, verbose_name='Request for Quotations')),
                ('interview_questions', models.TextField(blank=True, help_text='Document: Oral Interview Questions', null=True)),
                ('acquisition_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_lead', to=settings.AUTH_USER_MODEL)),
                ('alternate_contracting_officer_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.AlternateContractingOfficerRepresentative')),
                ('contracting_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ContractingOffice')),
                ('contracting_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ContractingOfficer')),
                ('contracting_officer_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ContractingOfficerRepresentative')),
                ('contracting_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ContractingSpecialist')),
                ('nda_signed', models.ManyToManyField(blank=True, related_name='ndas', to=settings.AUTH_USER_MODEL)),
                ('product_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_lead', to=settings.AUTH_USER_MODEL)),
                ('product_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy', to='projects.Project')),
                ('technical_evaluation_panel', models.ManyToManyField(blank=True, related_name='panels', to=settings.AUTH_USER_MODEL)),
                ('technical_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_lead', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Vendor')),
            ],
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='acquisition_lead',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='alternate_contracting_officer_representative',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='contracting_office',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='contracting_officer',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='contracting_officer_representative',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='contracting_specialist',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='nda_signed',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='product_lead',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='product_owner',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='project',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='technical_evaluation_panel',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='technical_lead',
        ),
        migrations.RemoveField(
            model_name='agilebpa',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='micropurchase',
            name='product_owner',
        ),
        migrations.RemoveField(
            model_name='micropurchase',
            name='project',
        ),
        migrations.RemoveField(
            model_name='micropurchase',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='openmarket',
            name='product_owner',
        ),
        migrations.RemoveField(
            model_name='openmarket',
            name='project',
        ),
        migrations.RemoveField(
            model_name='openmarket',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='software',
            name='product_owner',
        ),
        migrations.RemoveField(
            model_name='software',
            name='project',
        ),
        migrations.RemoveField(
            model_name='software',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='AgileBPA',
        ),
        migrations.DeleteModel(
            name='Micropurchase',
        ),
        migrations.DeleteModel(
            name='OpenMarket',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
    ]
