# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20161123_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='set_aside',
            field=models.CharField(blank=True, choices=[('AbilityOne', 'AbilityOne'), ('HUBZone Small Business', 'HUBZone Small Business'), ('Multiple Small Business Categories', 'Multiple Small Business Categories'), ('Other Than Small', 'Other Than Small'), ('Service Disabled Veteran-owned Small Business', 'Service Disabled Veteran-owned Small Business'), ('Small Business', 'Small Business'), ('Small Disadvantaged Business (includes Section 8a)', 'Small Disadvantaged Business (includes Section 8a)'), ('Veteran-Owned Small Business', 'Veteran-Owned Small Business'), ('Woman-Owned Small Business', 'Woman-Owned Small Business')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='procurement_method',
            field=models.CharField(blank=True, choices=[('Agile BPA', 'Agile BPA'), ('Micro-Purchase', 'Micro-Purchase')], max_length=200, null=True),
        ),
    ]
