# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20170131_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('Labor Hours', 'Labor Hours'), ('Time and Materials', 'Time and Materials'), ('Firm Fixed Price', 'Firm Fixed Price')], max_length=200, null=True),
        ),
    ]
