# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20170131_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='planned_award_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='planned_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='planned_issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
