# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20170201_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='github_repository',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub repository'),
        ),
    ]
