# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20170201_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
    ]
