# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_buy_github_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='award_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
