# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_buy_github_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='market_research',
            field=models.TextField(blank=True, null=True),
        ),
    ]
