# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20161129_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='rfq_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RFQ ID'),
        ),
    ]
