# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20161129_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
