# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_buy_market_research'),
        ('projects', '0026_buy_locked'),
    ]

    operations = [
    ]
