# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_merge_20161130_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agencies'},
        ),
    ]
