# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20161201_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_project', 'Can view non-public projects'),)},
        ),
    ]
