# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20161201_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_project', 'Can view non-public projects'), ('sign_nda', 'Can sign an NDA, either blanket or specific'))},
        ),
    ]
