# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_project_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(help_text='You may select from users who have signed the blanket NDA.', to=settings.AUTH_USER_MODEL),
        ),
    ]
