# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0033_buy_technical_evaluation_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='nda_signed',
            field=models.ManyToManyField(blank=True, related_name='ndas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buy',
            name='technical_evaluation_panel',
            field=models.ManyToManyField(blank=True, related_name='panels', to=settings.AUTH_USER_MODEL),
        ),
    ]
