# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 03:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0034_auto_20161204_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgileBPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dollars', models.PositiveIntegerField(null=True)),
                ('public', models.BooleanField(default=False)),
                ('contractual_history', models.TextField(default='This is the first contract for this functionality.')),
                ('base_period_length', models.CharField(blank=True, max_length=100, null=True)),
                ('option_periods', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('option_period_length', models.CharField(blank=True, max_length=100, null=True)),
                ('procurement_method', models.CharField(default='Agile Development Services BPA Order', editable=False, max_length=200)),
                ('set_aside_status', models.CharField(blank=True, choices=[('AbilityOne', 'AbilityOne'), ('HUBZone Small Business', 'HUBZone Small Business'), ('Multiple Small Business Categories', 'Multiple Small Business Categories'), ('Other Than Small', 'Other Than Small'), ('Service Disabled Veteran-owned Small Business', 'Service Disabled Veteran-owned Small Business'), ('Small Business', 'Small Business'), ('Small Disadvantaged Business (includes Section 8a)', 'Small Disadvantaged Business (includes Section 8a)'), ('Veteran-Owned Small Business', 'Veteran-Owned Small Business'), ('Woman-Owned Small Business', 'Woman-Owned Small Business')], max_length=200, null=True, verbose_name='Set-aside Status')),
                ('rfq_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='RFQ ID')),
                ('github_repository', models.URLField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('qasp', models.TextField(blank=True, null=True, verbose_name='QASP')),
                ('acquisition_plan', models.TextField(blank=True, null=True)),
                ('market_research', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('contracting_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ContractingOffice')),
                ('contracting_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ContractingOfficer')),
                ('contracting_officer_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ContractingOfficerRepresentative')),
                ('contracting_specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ContractingSpecialist')),
                ('nda_signed', models.ManyToManyField(blank=True, related_name='ndas', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='projects.Project')),
                ('technical_evaluation_panel', models.ManyToManyField(blank=True, related_name='panels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='buy',
            name='contracting_office',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='contracting_officer',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='contracting_officer_representative',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='contracting_specialist',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='nda_signed',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='project',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='technical_evaluation_panel',
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='agencyoffice',
            options={'ordering': ['agency', 'name']},
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
