# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20161207_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Micropurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dollars', models.PositiveIntegerField(null=True)),
                ('public', models.BooleanField(default=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micropurchase', to='projects.Project')),
            ],
            options={
                'verbose_name': 'Micro-purchase',
            },
        ),
        migrations.AlterModelOptions(
            name='agilebpa',
            options={'verbose_name': 'Agile BPA Order'},
        ),
        migrations.AlterField(
            model_name='agilebpa',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agilebpa', to='projects.Project'),
        ),
    ]
