# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20161207_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='micropurchase',
            name='procurement_method',
            field=models.CharField(default='Micro-purchase', editable=False, max_length=200),
        ),
    ]
