# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_micropurchase_procurement_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dollars', models.PositiveIntegerField(null=True)),
                ('public', models.BooleanField(default=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openmarket', to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dollars', models.PositiveIntegerField(null=True)),
                ('public', models.BooleanField(default=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
