language: python
python:
- '3.5'
addons:
  postgresql: '9.4'
install: pip install -r requirements.txt
cache:
  directories:
  - "$HOME/.cache/pip"
script:
- "./manage.py collectstatic --noinput -v 0"
- py.test --cov=acquisitions --cov=projects --cov=team --cov=web
- codeclimate-test-reporter
- bandit -r .
after_script:
- npm install -g pa11y-crawl
- pa11y-crawl --run "./manage.py runserver" --ci http://localhost:8000
before_deploy:
- export PATH=$HOME:$PATH
- travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0"
- tar xzvf $HOME/cf.tgz -C $HOME
- cf install-plugin autopilot -f -r CF-Community
deploy:
- provider: script
  script: "./bin/deploy staging"
  skip_cleanup: true
  on:
    branch: develop
env:
  global:
  - CF_USERNAME=6c319632-cc9c-47c7-bda4-64d6abc4609d
  - secure: WVLNIdDJeGUu3G+N5wbPvfEbeTZ6yDycCN5rVaQkmmqCE+CpDexkQrw02aTL2LhrDguNSsAmdRGGl2LNwD5cowb7fO14Y7lM3uqw5ZygMMozzBNh/S9PXUYfxKjETU2o7WibmSg5VLaaQBOaK2MOLAOE/Vmzvp7dkyWZU3gYCBdnYANf6fw5gEnrZvgldXVSshVfGvCkzinnU3DtnQmBO/HFlTmBp6G1rTj3QoM/U+9hLi7NDJ6Wt0dL4iSyStRNaAPrfvvX1akSdje/7peeriOZh1zekI3FRi+VyhMtlmD3/Xnf43nMO5uyYBSwQqV/ZOk7jmHraYrCN441KOVKrHoaF1gz0wI7UKmah+7tzH2iWoyWbwKxLNRSmGgNBVP8o7tZJNE1zo2sxryqMddb3e5aqKxscX4psd6/qd6lBhknUUG9V99pwLUvYI4QT6/iaVLTQ7mmo22pTNLGyT5gfLdrsFiTdMTMtwD+AexHaaCIEs0yBraD/IEjw5JsxHqUj5dvkvi7UL63JQo2UGL7E91QKtR5TpbxBRPRg1/QVaLJB4sZLrIAT8762OQ2ynxF6Z+KCb8gY76F9N/NwDdirrmHrp+jTyAfO/PqnjaAI36HtC0HxOEaTGOTbLtThutfiZDrUcP3efnTumO+jWW3nU8RlrUUSv1g4NIX2w9vYHw=
  - secure: S+vtwo31/xp2edN0gWAhyclG/mQm2wzZ8l73WreJXMY8ovLByOFClEIawLxe8yKlW3yE5ZH+Dze6ypjZIh1pgCltbLqdifkys5ww4m5XOI4jmYed8XL5mco2YbGRdAwZdGmkzGlDArTgvxEBXxbDCJwcvkxO/E11BotWPBGGbI8IqCmkMEoQONVpptDAtcm/gVO0AntkkCo51jTn0CuCARd6m6d7G3O0ycJV/LOutsW0VmGV1I57AicWV6HClr430IyEzJ0w54d22oGV/S17GfERsn9rDhrXu8qAzMX+A6lsw5GpDVBipyBQ8wtHO/HUH8v6yEVIx6ko27+lQFsKG4QpvKVxFD8LxlYewhyZAcT71Rcp/NNWNR+YJd3oICKLky9o4HeE/9G59RA+ZS7Ncr7ip8Krac4hTs39llzqE57YHuVRqm3QY9R0cf49n42c3eGma+y3mrZT1h6zRHwoNzpxrkh8/VpenzhCXVa4us7U3fjJ1svA2KtOqr9dn8eQdH7HHg8xZf0DpFrkcejmkYL5GwPrGOR83PZkHgrgBvXeCBMQq+8ZyFiOubWH3pvHrTb1F2tMShwVvzbxwaBQMIq/36NRFMJ2WYxxkkJmyxGaN/y7FCR1stXAXVCMvSSJzuMbTpENILkWTGa6G5v/qnBGyWo0SrNkHK4IyEwc81M=
