language: python
python:
- '3.5'
addons:
  postgresql: '9.4'
install: pip install -r requirements.txt
cache:
  directories:
  - "$HOME/.cache/pip"
script:
  - ./manage.py collectstatic --noinput -v 0
  - py.test --cov=acquisitions --cov=projects --cov=team --cov=web --cov=nda
  - codeclimate-test-reporter
  - bandit -r .
after_script:
- npm install -g pa11y-crawl
- pa11y-crawl --run "./manage.py runserver" --ci http://localhost:8000
before_deploy:
- export PATH=$HOME:$PATH
- travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0"
- tar xzvf $HOME/cf.tgz -C $HOME
- cf install-plugin autopilot -f -r CF-Community
deploy:
- provider: script
  script: "./bin/deploy staging"
  skip_cleanup: true
  on:
    branch: develop
env:
  global:
  - CF_USERNAME=6c319632-cc9c-47c7-bda4-64d6abc4609d
  - secure: Nf375s8h8cSMgKdSR3wpCl26pwaYAhbxHiJ9tf4rWtJNZKv+WeX/hgsv+EG+oztyMz8QYOaSsONz3BszMG/zi3JOov/mZIRm6kQhGexzTSXh3sTZU+/3ZGuX2SQORKIl0NMLnV2KIvsGrKskCSkc4jR6jvMmNQscU6zp6PcmfPQrfZtnHv8Iz9okCjvZMD+iWTYeV0Y9wtNk15beNbk/B7HKyR6UyQ1ELDbyK99yp2GlBJkqqM0n+lPcYq3Y6VhEetFvuw6wwR0CasVFhP+1MCooRkoC96oF7/gh2UBqQFsHazCvK1wAx2Qv7kfZy0oASIkOvqT2VJ0+YPj5eR2WVbl6jkrV6CVMhZZNulR5K3engKGYCgJN1ZawkyDNeI5Soxc11kA7nB+khshTYgFUXBiPFBW1TLvDd8h5aTlvsQHhyHcw6PJi8ioREdRZ4+E8jzF7xCOM+JGw5M7l1VMliIevBB4FmJbSwrInYYokFJRIo3zWtkDWIlZOUjdkSiWLV560I9tBEiFwTPXmQlgLPwWo5FKMJZia6d1s9UpxXxIgSgxUL0vcqt+vrAu3zEnKvMGtlNWzNocjgR65YHEeWGgxiBDfOYmdYhQCJTHh1REY9T3URluQ5FlezHiTqzyqsU0aqmP+3Wysptk3p2dIGZUmCIeGkgwMQcu0FZvP7og=
  - secure: S+vtwo31/xp2edN0gWAhyclG/mQm2wzZ8l73WreJXMY8ovLByOFClEIawLxe8yKlW3yE5ZH+Dze6ypjZIh1pgCltbLqdifkys5ww4m5XOI4jmYed8XL5mco2YbGRdAwZdGmkzGlDArTgvxEBXxbDCJwcvkxO/E11BotWPBGGbI8IqCmkMEoQONVpptDAtcm/gVO0AntkkCo51jTn0CuCARd6m6d7G3O0ycJV/LOutsW0VmGV1I57AicWV6HClr430IyEzJ0w54d22oGV/S17GfERsn9rDhrXu8qAzMX+A6lsw5GpDVBipyBQ8wtHO/HUH8v6yEVIx6ko27+lQFsKG4QpvKVxFD8LxlYewhyZAcT71Rcp/NNWNR+YJd3oICKLky9o4HeE/9G59RA+ZS7Ncr7ip8Krac4hTs39llzqE57YHuVRqm3QY9R0cf49n42c3eGma+y3mrZT1h6zRHwoNzpxrkh8/VpenzhCXVa4us7U3fjJ1svA2KtOqr9dn8eQdH7HHg8xZf0DpFrkcejmkYL5GwPrGOR83PZkHgrgBvXeCBMQq+8ZyFiOubWH3pvHrTb1F2tMShwVvzbxwaBQMIq/36NRFMJ2WYxxkkJmyxGaN/y7FCR1stXAXVCMvSSJzuMbTpENILkWTGa6G5v/qnBGyWo0SrNkHK4IyEwc81M=
