language: python
python:
- '3.5'
addons:
  postgresql: '9.4'
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
cache:
  directories:
  - "$HOME/.cache/pip"
script:
- "./manage.py collectstatic --noinput -v 0"
- py.test --cov=acquisitions --cov=projects --cov=team --cov=web --cov=nda
- codeclimate-test-reporter
- bandit -r .
after_script:
- npm install -g pa11y-crawl
- pa11y-crawl --run "./manage.py runserver" --ci http://localhost:8000
before_deploy:
- export PATH=$HOME:$PATH
- travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0"
- tar xzvf $HOME/cf.tgz -C $HOME
- cf install-plugin autopilot -f -r CF-Community
deploy:
- provider: script
  script: "./bin/deploy staging"
  skip_cleanup: true
  on:
    branch: develop
env:
  global:
  - CF_USERNAME=c9a300d8-2610-424b-94a0-14e321420176
  - secure: Nf375s8h8cSMgKdSR3wpCl26pwaYAhbxHiJ9tf4rWtJNZKv+WeX/hgsv+EG+oztyMz8QYOaSsONz3BszMG/zi3JOov/mZIRm6kQhGexzTSXh3sTZU+/3ZGuX2SQORKIl0NMLnV2KIvsGrKskCSkc4jR6jvMmNQscU6zp6PcmfPQrfZtnHv8Iz9okCjvZMD+iWTYeV0Y9wtNk15beNbk/B7HKyR6UyQ1ELDbyK99yp2GlBJkqqM0n+lPcYq3Y6VhEetFvuw6wwR0CasVFhP+1MCooRkoC96oF7/gh2UBqQFsHazCvK1wAx2Qv7kfZy0oASIkOvqT2VJ0+YPj5eR2WVbl6jkrV6CVMhZZNulR5K3engKGYCgJN1ZawkyDNeI5Soxc11kA7nB+khshTYgFUXBiPFBW1TLvDd8h5aTlvsQHhyHcw6PJi8ioREdRZ4+E8jzF7xCOM+JGw5M7l1VMliIevBB4FmJbSwrInYYokFJRIo3zWtkDWIlZOUjdkSiWLV560I9tBEiFwTPXmQlgLPwWo5FKMJZia6d1s9UpxXxIgSgxUL0vcqt+vrAu3zEnKvMGtlNWzNocjgR65YHEeWGgxiBDfOYmdYhQCJTHh1REY9T3URluQ5FlezHiTqzyqsU0aqmP+3Wysptk3p2dIGZUmCIeGkgwMQcu0FZvP7og=
  - secure: W+LzIxX8OtGsunesEKMo6rJHqS9n827c+a7o2lDbv84xn3ucb7dk526QOesv5+5hs9uKmhkIgIdh4lQhxqrl4mGo5T3dTfQhPClH3CWeOi47qqSTRKOw2XZrc1Ef/FW7NBIknovxtFvOusKGK/Y70Yhgx2wazJLj2xpIW1E8ZNnsY6Lt9NLFLp/+AACHT70ceWxn20OK5hyjAOeBoaeT08mogvAl7np97hY+3oK5BR6ZOIn2+6ToUle6vBFUyTuc/rK409bvwKLbN/PPu4BaH8glHZmuDmyS0LqzOpatfaLGbEvrLlaZv/wiR2geMOJaG0elp8zi8AcRJ6I0cqnWd0+WSKUfBMlGoEhp24YZq4f1+10vOYI4Pv0BwKmAMlxHw7gjmeWTdlPGALrwXrvUZ6+UEgjLzd35Xwxbu89VWmdYuBlrhQKj1kk06Rwp5pdl6FZTHJm3YKp5pJfZxSCgQxmw0IWKxjg0nBV9EvWofdXDBXxQUxeYWd3Zv22OA7Np69vc5VNDWknGBKyUTapd+0OLru+R1GMNelVAq7oFpD89IYtxjBpESFrybFBoRMhz6MAkGA+yyG7d4QCAMeaUJWTKyTxGNznQXDMWNwTQ0k0+/vA0xbL/zcX59V2ZBqhb5HP55CKBucF+yHgZnzYyzNQK03oMWjM1mo3iyWgQ7ik=
