language: python
python:
- '3.5'
addons:
  postgresql: '9.4'
install: pip install -r requirements.txt
cache:
  directories:
  - "$HOME/.cache/pip"
script: "./manage.py collectstatic --noinput -v 0 && py.test --cov=acquisitions --cov=projects --cov=team --cov=web && codeclimate-test-reporter"
after_script:
- npm install -g pa11y-crawl
- pa11y-crawl --run "./manage.py runserver" --ci http://localhost:8000
before_deploy:
- export PATH=$HOME:$PATH
- travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.15.0"
- tar xzvf $HOME/cf.tgz -C $HOME
- cf install-plugin autopilot -f -r CF-Community
deploy:
- provider: script
  script: "./bin/deploy staging"
  skip_cleanup: true
  on:
    branch: develop
