# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='update',
            new_name='content',
        ),
    ]
