# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20161125_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
