# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
