# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_squashed_0011_auto_20161105_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Role'),
        ),
    ]
