# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20161029_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='slack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
