# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20161029_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
