# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_teammate_read_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='teammate',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Role'),
            preserve_default=False,
        ),
    ]
