# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20161031_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='photo',
            field=models.ImageField(default='/team/photos/default.png', upload_to='/team/photos'),
        ),
    ]
