# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_remove_teammate_read_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammate',
            options={'permissions': (('view_private', 'Can view private team info'),)},
        ),
    ]
